---
title: 世帯収入の模擬データを作る
author: ''
date: '2022-08-07'
slug: []
categories:
  - MyFunction
tags:
  - Epidemiology
  - R
  - MyFunction
subtitle: ''
description: ''
image: ''
output:
  blogdown::html_page:
    highlight: default
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<div id="やること" class="section level1">
<h1>やること</h1>
<p>e-statの令和元年度国民生活基礎調査に基づいて、世帯収入のダミーデータを生む関数を作ります。<br>
source: <a href="https://www.e-stat.go.jp/dbview?sid=0003442017">e-stat</a></p>
<p>なお、単身世帯・性別等の個別化された世帯収入ではなく、平均的な日本世帯収入を生むだけです。
個人の世帯収入として扱うのは不十分だと思いますが、データ遊びする分には十分遊べるかと思います。</p>
<p>関数の内容は以下の通りです。</p>
<ul>
<li>ID, sex, income (confounder), x (binary exposure), y (binary outcome) を含むデータを作成する</li>
<li>incomeは交絡: incomeが少ないほどx and yが発生しやすい (i.e., confounding bias away from the null)</li>
<li>引数: n_sample=人数、risk_ratio=曝露によるリスク比</li>
</ul>
</div>
<div id="関数" class="section level1">
<h1>関数</h1>
<div id="関数の作成" class="section level2">
<h2>関数の作成</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># incomeデータを国民生活基礎調査に基づいて作成</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>MakeIncomeData <span class="ot">&lt;-</span> <span class="cf">function</span>(){</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  income_cat <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  min_income <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">500000</span>, <span class="dv">1000000</span>, <span class="dv">1500000</span>, <span class="dv">2000000</span>, <span class="dv">2500000</span>, <span class="dv">3000000</span>, <span class="dv">3500000</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                  <span class="dv">4000000</span>, <span class="dv">4500000</span>, <span class="dv">5000000</span>, <span class="dv">5500000</span>, <span class="dv">6000000</span>, <span class="dv">6500000</span>, <span class="dv">7000000</span>, <span class="dv">7500000</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                  <span class="dv">8000000</span>, <span class="dv">8500000</span>, <span class="dv">9000000</span>, <span class="dv">9500000</span>, <span class="dv">10000000</span>, <span class="dv">11000000</span>, <span class="dv">12000000</span>, <span class="dv">15000000</span>, <span class="dv">20000000</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  max_income <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">499999</span>, <span class="dv">999999</span>, <span class="dv">1499999</span>, <span class="dv">1999999</span>, <span class="dv">2499999</span>, <span class="dv">2999999</span>, <span class="dv">3499999</span>, <span class="dv">3999999</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                  <span class="dv">4499999</span>, <span class="dv">4999999</span>, <span class="dv">5499999</span>, <span class="dv">5999999</span>, <span class="dv">6499999</span>, <span class="dv">6999999</span>, <span class="dv">7499999</span>, <span class="dv">7999999</span>, <span class="dv">8499999</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                  <span class="dv">8999999</span>, <span class="dv">9499999</span>, <span class="dv">9999999</span>, <span class="dv">10999999</span>, <span class="dv">11999999</span>, <span class="dv">14999999</span>, <span class="dv">19999999</span>, <span class="dv">100000000</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  df_income <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">income_cat =</span> income_cat,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">min_income =</span> min_income, </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                          <span class="at">max_income =</span> max_income)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df_income)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># ID, sex, income (confounder), x (binary exposure), y (binary outcome) を含むデータを作成する </span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># incomeが少ないほどx and yが発生しやすい-&gt; confounding bias away from the null</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 引数: n_sample=人数、risk_ratio=曝露によるリスク比</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>MakeData <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">n_sample=</span><span class="dv">1000</span>, <span class="at">risk_ratio=</span><span class="fl">1.5</span>){</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># income data &amp; income_threshold</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  income_cat <span class="ot">&lt;-</span> <span class="fu">MakeIncomeData</span>()</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  income_threshold <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.012</span>, <span class="fl">0.064</span>, <span class="fl">0.127</span>, <span class="fl">0.19</span>, <span class="fl">0.259</span>, <span class="fl">0.326</span>, <span class="fl">0.397</span>, <span class="fl">0.454</span>, </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>                        <span class="fl">0.51</span>, <span class="fl">0.559</span>, <span class="fl">0.608</span>, <span class="fl">0.646</span>, <span class="fl">0.692</span>, <span class="fl">0.726</span>, <span class="fl">0.759</span>, <span class="fl">0.788</span>,</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>                        <span class="fl">0.814</span>, <span class="fl">0.837</span>, <span class="fl">0.859</span>, <span class="fl">0.878</span>, <span class="fl">0.909</span>, <span class="fl">0.928</span>, <span class="fl">0.966</span>, <span class="fl">0.987</span>, <span class="dv">1</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># make data frame</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ID =</span> <span class="dv">1</span><span class="sc">:</span>n_sample)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">rbinom</span>(<span class="fu">nrow</span>(df), <span class="dv">1</span>, <span class="fl">0.5</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">prob_income =</span> <span class="fu">runif</span>(n_sample, <span class="at">min=</span><span class="dv">0</span>, <span class="at">max=</span><span class="dv">1</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">income_cat =</span> <span class="fu">cut</span>(prob_income,</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>                            <span class="at">breaks =</span> income_threshold,</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>                            <span class="at">right =</span> <span class="cn">TRUE</span>, </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>                            <span class="at">include.lowest =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    )) <span class="sc">%&gt;%</span> </span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">income_cat =</span> <span class="fu">as.integer</span>(income_cat))</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">left_join</span>(df, income_cat, <span class="at">by =</span> <span class="st">&quot;income_cat&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(ID, sex, income_cat, min_income, max_income) <span class="sc">%&gt;%</span> </span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">income =</span> <span class="fu">runif</span>(n_sample, <span class="at">min =</span> min_income, <span class="at">max =</span> max_income)) <span class="sc">%&gt;%</span> </span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(ID, sex, income)</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">income_cat =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&lt;</span> <span class="dv">2500000</span> <span class="sc">~</span> <span class="st">&quot;&lt;250&quot;</span>,</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&gt;=</span> <span class="dv">2500000</span> <span class="sc">&amp;</span> income <span class="sc">&lt;</span> <span class="dv">4000000</span> <span class="sc">~</span> <span class="st">&quot;&lt;400&quot;</span>,</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&gt;=</span> <span class="dv">4000000</span> <span class="sc">&amp;</span> income <span class="sc">&lt;</span> <span class="dv">7000000</span> <span class="sc">~</span> <span class="st">&quot;&lt;700&quot;</span>,</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&gt;=</span> <span class="dv">7000000</span> <span class="sc">~</span> <span class="st">&quot;≥700&quot;</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>    <span class="at">income_cat =</span> <span class="fu">factor</span>(income_cat, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;&lt;250&quot;</span>, <span class="st">&quot;&lt;400&quot;</span>, <span class="st">&quot;&lt;700&quot;</span>, <span class="st">&quot;≥700&quot;</span>))) </span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 曝露の発生確率と曝露(0/1)を定義</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">x_prob =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&lt;</span> <span class="dv">2500000</span> <span class="sc">~</span> <span class="fl">0.25</span>,</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&gt;=</span> <span class="dv">2500000</span> <span class="sc">&amp;</span> income <span class="sc">&lt;</span> <span class="dv">4000000</span> <span class="sc">~</span> <span class="fl">0.2</span>,</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&gt;=</span> <span class="dv">4000000</span> <span class="sc">&amp;</span> income <span class="sc">&lt;</span> <span class="dv">7000000</span> <span class="sc">~</span> <span class="fl">0.15</span>,</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&gt;=</span> <span class="dv">7000000</span> <span class="sc">~</span> <span class="fl">0.1</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>    )) <span class="sc">%&gt;%</span> </span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">x =</span> <span class="fu">rbinom</span>(<span class="fu">nrow</span>(df), <span class="dv">1</span>, x_prob)) <span class="co"># 定めた曝露発生確率の二項分布に従って曝露を決定</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 曝露しているとイベント発生確率がrisk_ratio倍になる</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">y_prob =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&lt;</span> <span class="dv">2500000</span> <span class="sc">~</span> <span class="fl">0.25</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> x<span class="sc">*</span>(risk_ratio<span class="dv">-1</span>)),</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&gt;=</span> <span class="dv">2500000</span> <span class="sc">&amp;</span> income <span class="sc">&lt;</span> <span class="dv">4000000</span> <span class="sc">~</span> <span class="fl">0.2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> x<span class="sc">*</span>(risk_ratio<span class="dv">-1</span>)),</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&gt;=</span> <span class="dv">4000000</span> <span class="sc">&amp;</span> income <span class="sc">&lt;</span> <span class="dv">7000000</span> <span class="sc">~</span> <span class="fl">0.15</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> x<span class="sc">*</span>(risk_ratio<span class="dv">-1</span>)),</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>      income <span class="sc">&gt;=</span> <span class="dv">7000000</span> <span class="sc">~</span> <span class="fl">0.1</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> x<span class="sc">*</span>(risk_ratio<span class="dv">-1</span>))</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>    )) <span class="sc">%&gt;%</span> </span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">rbinom</span>(<span class="fu">nrow</span>(df), <span class="dv">1</span>, y_prob)) <span class="sc">%&gt;%</span> </span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>x_prob, <span class="sc">-</span>y_prob)</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df)</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
</div>
<div id="関数の確認" class="section level2">
<h2>関数の確認</h2>
<p>使い方はこんな感じ</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">MakeData</span>(<span class="at">n_sample =</span> <span class="dv">1000</span>, <span class="at">risk_ratio =</span> <span class="fl">2.0</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>##   ID sex  income income_cat x y
## 1  1   0 9057019       ≥700 1 0
## 2  2   1 4096104       &lt;700 0 0
## 3  3   1 1309235       &lt;250 0 0
## 4  4   1 3299529       &lt;400 0 0
## 5  5   1 7530942       ≥700 0 0
## 6  6   1 3349626       &lt;400 0 1</code></pre>
<p>所得の分布はこの通り。200-300万円程度でピークが来ていて、右に長い裾を引くという日本世帯収入の特徴をつかめていると思います。</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mean_income <span class="ot">&lt;-</span> <span class="fu">mean</span>(df<span class="sc">$</span>income)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>median_income <span class="ot">&lt;-</span> <span class="fu">median</span>(df<span class="sc">$</span>income)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>mean_text <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;mean: &quot;</span>, <span class="fu">as.character</span>(<span class="fu">round</span>((mean_income<span class="sc">/</span><span class="dv">1000000</span>), <span class="at">digits=</span><span class="dv">2</span>)), <span class="st">&quot; million yen&quot;</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>median_text <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;median: &quot;</span>, <span class="fu">as.character</span>(<span class="fu">round</span>((median_income<span class="sc">/</span><span class="dv">1000000</span>), <span class="at">digits=</span><span class="dv">2</span>)), <span class="st">&quot; million yen&quot;</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>subtitle <span class="ot">&lt;-</span> <span class="fu">paste0</span>(median_text, <span class="st">&quot; (orange), &quot;</span>, mean_text, <span class="st">&quot; (skyblue)&quot;</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x =</span> income)) <span class="sc">+</span> </span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_income, <span class="at">linetype =</span> <span class="dv">2</span>, <span class="at">colour =</span> <span class="st">&quot;skyblue&quot;</span>) <span class="sc">+</span> </span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> median_income, <span class="at">linetype =</span> <span class="dv">2</span>, <span class="at">colour =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span> </span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20000000</span>)) <span class="sc">+</span> </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;simulated distribution of income&quot;</span>, subtitle)</span></code></pre></div>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>実際の分布は次のとおりです (source: <a href="https://www.mhlw.go.jp/toukei/saikin/hw/k-tyosa/k-tyosa19/index.html">URL</a>)。</p>
<div class="figure">
<img src="{{< blogdown/postref >}}index_files/income.png" alt="" />
<p class="caption">所得の分布状況 (令和元年度国民生活基礎調査)</p>
</div>
<p>国民生活基礎調査をもとにデータをシミュレーションしているから当然なんだけど、いいデモデータになるでしょ？</p>
<p>一応、xとyとの関連も確認。
単純にxとyをlog-binomialで回帰分析したモデルと、収入を4カテゴリ (250万円未満 / 250-400万円 / 400-700万円 / 700万円以上) に分けて調整したモデルの2つを実行します。</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>crude <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> df, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;log&quot;</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(crude)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x, family = binomial(link = &quot;log&quot;), data = df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.0579  -0.6398  -0.6398  -0.6398   1.8368  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.68688    0.07274  -23.19  &lt; 2e-16 ***
## x            0.83958    0.11501    7.30 2.88e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1068.8  on 999  degrees of freedom
## Residual deviance: 1026.6  on 998  degrees of freedom
## AIC: 1030.6
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(crude)) <span class="co"># risk ratio</span></span></code></pre></div>
<pre><code>## (Intercept)           x 
##   0.1850962   2.3153989</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>adjusted <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> x <span class="sc">+</span> income_cat, <span class="at">data =</span> df, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;log&quot;</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(adjusted)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ x + income_cat, family = binomial(link = &quot;log&quot;), 
##     data = df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.2228  -0.7399  -0.6391  -0.5278   2.0200  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -1.4293     0.1049 -13.628  &lt; 2e-16 ***
## x                0.7879     0.1149   6.856 7.08e-12 ***
## income_cat&lt;400  -0.2383     0.1557  -1.531   0.1259    
## income_cat&lt;700  -0.2596     0.1400  -1.855   0.0636 .  
## income_cat≥700  -0.6109     0.1755  -3.481   0.0005 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1068.8  on 999  degrees of freedom
## Residual deviance: 1012.8  on 995  degrees of freedom
## AIC: 1022.8
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(adjusted)) <span class="co"># risk ratio</span></span></code></pre></div>
<pre><code>##    (Intercept)              x income_cat&lt;400 income_cat&lt;700 income_cat≥700 
##      0.2394715      2.1987082      0.7879789      0.7713427      0.5428814</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(adjusted)) <span class="co"># 95%CI</span></span></code></pre></div>
<pre><code>##                    2.5 %    97.5 %
## (Intercept)    0.1934482 0.2914440
## x              1.7452555 2.7416437
## income_cat&lt;400 0.5720032 1.0622755
## income_cat&lt;700 0.5838765 1.0102595
## income_cat≥700 0.3800548 0.7554868</code></pre>
<p>risk ratioは2.0で設定したところ、データではRR=2.20 になっていました。
おそらく想定した通りにちゃんと動いているでしょう。</p>
<p>また、交絡に関して確認すると、
crudeだと RR=2.32 で、収入を調整したadjustedだと RR=2.20 となっていました。
したがって、収入がbias away from the nullになっていることも確認できました。</p>
<p><br></p>
</div>
</div>
<div id="実際に使う場合のtips" class="section level1">
<h1>実際に使う場合のtips</h1>
<p>実際にこの関数を動かすときは、関数を.Rで作成して保存し、解析コードの.R/.Rmdから読み出すといいでしょう。</p>
<p>例として、以下のディレクトリ構造でコードを書いていたとします。</p>
<p>root directory/<br>
├ index.Rmd (← 今書いてるドキュメント) <br>
└ index_files/ (sub directory)<br>
 └ makedata.R <br></p>
<p>こういう構造の場合、以下のコードで.Rをソースコードとして読むことが可能です。</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;./index_files/makedata.R&quot;</span>) <span class="co"># 今回使う自作関数をまとめた.Rファイル</span></span></code></pre></div>
<p>そんじゃあね。</p>
</div>
